class AnimalNameMapper {
  static const Map<String, String> englishToPortuguese = {
    // 🟢 COMUNS
    "dog": "Cachorro",
    "domestic dog": "Cachorro",
    "cat": "Gato",
    "chicken": "Galinha",
    "rooster": "Galo",
    "duck": "Pato",
    "pigeon": "Pombo",
    "sparrow": "Pardal",
    "turtle": "Tartaruga",
    "gecko": "Lagartixa",
    "toad": "Sapo",
    "frog": "Rã",
    "butterfly": "Borboleta",
    "ant": "Formiga",
    "bee": "Abelha",
    "mosquito": "Mosquito",
    "cockroach": "Barata",
    "crab": "Caranguejo",
    "capybara": "Capivara",
    "horse": "Cavalo",
    "cow": "Vaca",
    "pig": "Porco",
    "goat": "Cabra",
    "sheep": "Ovelha",
    "rabbit": "Coelho",
    "hamster": "Hamster",
    "goldfish": "Peixe-dourado",
    "tilapia": "Tilápia",
    "sardine": "Sardinha",
    "alligator": "Jacaré",
    "iguana": "Iguana",
    "opossum": "Gambá",
    "coati": "Quati",
    "capuchin monkey": "Macaco-prego",
    "golden lion tamarin": "Mico-leão-dourado",
    "hyacinth macaw": "Arara-azul",
    "scarlet macaw": "Arara-vermelha",
    "blue-and-yellow macaw": "Arara-canindé",
    "toucan": "Tucano",
    "great kiskadee": "Bem-te-vi",
    "owl": "Coruja",
    "hawk": "Gavião",
    "heron": "Garça",
    "vulture": "Urubu",
    "swallow": "Andorinha",
    "caracara": "Carcará",
    "lobster": "Lagosta",
    "teal": "Marreco",
    "parrot": "Papagaio",
    "cockatiel": "Calopsita",

    // 🟡 INCOMUNS
    "anteater": "Tamanduá",
    "giant anteater": "Tamanduá-bandeira",
    "maned wolf": "Lobo-guará",
    "puma": "Onça-parda",
    "wild boar": "Javali",
    "tapir": "Anta",
    "anaconda": "Sucuri",
    "boa constrictor": "Jiboia",
    "giant otter": "Ariranha",
    "sloth": "Bicho-preguiça",
    "armadillo": "Tatu",
    "pill bug": "Tatuzinho",
    "coral snake": "Cobra-coral",
    "rattlesnake": "Cascavel",
    "manatee": "Peixe-boi",
    "piranha": "Piranha",
    "grouper": "Garoupa",
    "fruit bat": "Morcego-fruta",
    "vampire bat": "Morcego-vampiro",
    "wildcat": "Gato-do-mato",
    "jaguarundi": "Jaguarundi",
    "raccoon": "Guaxinim",
    "pelican": "Pelicano",
    "albatross": "Albatroz",
    "magellanic penguin": "Pinguim-magalhães",
    "seagull": "Gaivota",
    "stingray": "Arraia",
    "pufferfish": "Baiacu",
    "sunfish": "Peixe-lua",
    "clownfish": "Peixe-palhaço",
    "moray eel": "Moreia",
    "octopus": "Polvo",
    "squid": "Lula",
    "shrimp": "Camarão",
    "scorpion": "Escorpião",
    "tarantula": "Caranguejeira",
    "praying mantis": "Louva-a-deus",
    "rhinoceros beetle": "Besouro-rinoceronte",
    "cicada": "Cigarra",
    "dragonfly": "Libélula",
    "grasshopper": "Gafanhoto",
    "cricket": "Grilo",
    "deer": "Veado",
    "howler monkey": "Bugio",
    "common marmoset": "Mico-estrela",

    // 🔴 RAROS
    "jaguar": "Onça-pintada",
    "harpy eagle": "Harpia",
    "sea lion": "Lobo-marinho",
    "amazon river dolphin": "Boto-cor-de-rosa",
    "black lion tamarin": "Mico-leão-preto",
    "leatherback turtle": "Tartaruga-de-couro",
    "golden eagle": "Águia-real",
    "hammerhead shark": "Tubarão-martelo",
    "great white shark": "Tubarão-branco",
    "humpback whale": "Baleia-jubarte",
    "spinner dolphin": "Golfinho-rotador",
    "giant salamander": "Salamandra",
    "king crab": "Caranguejo-real",
    "ferret": "Furão",
    "otter": "Lontra",
    "paca": "Paca",
    "agouti": "Cutia",
    "collared peccary": "Caititu",
    "white-lipped peccary": "Queixada",
    "ocelot": "Gato-maracajá",

    // 🟣 LENDÁRIOS (mapeados para espécie real equivalente)
    "black jaguar": "Onça-preta",

    "black caiman": "Jacaré-açu",
    "giant tortoise": "Tartaruga-gigante",
    "amazonian manatee": "Peixe-boi-amazônico",
    "blue whale": "Baleia-azul",
    "grey eagle": "Águia-cinzenta",
  };
}
